bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users:
- name: root
  password: $2a$10$0evpPr1ZOWAdVYRlKdxubuEPdc4Z97IaYVOojzKZ6ovwmPFFFsqCC
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 0.0.0.0
  port: 53
  statistics_interval: 90
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 1
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: 10.10.10.2
  blocking_ipv6: '::'
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: false
  upstream_dns:
  - https://doh.opendns.com/dns-query
  - https://dns.alidns.com/dns-query
  - https://i.233py.com/dns-query
  - https://dns.google/dns-query
  - https://rubyfish.cn/dns-query
  - https://1.1.1.1/dns-query
  upstream_dns_file: ""
  bootstrap_dns:
  - 223.5.5.5
  - 223.6.6.6
  - 2400:3200::1
  - 2400:3200:baba::1
  all_servers: true
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  cache_size: 0
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: true
  enable_dnssec: true
  edns_client_subnet: true
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites:
  - domain: cn.bing.com
    answer: 13.107.21.200
  - domain: bing.com
    answer: 13.107.21.200
  - domain: r.bing.com
    answer: 204.79.197.200
  - domain: www.bing.com
    answer: 13.107.21.200
  blocked_services: []
  local_domain_name: lan
  resolve_clients: true
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: false
  url: https://banbendalao.coding.net/p/adgk/d/ADgk/git/raw/master/ADgk.txt
  name: ADgk
  id: 1607147733
- enabled: true
  url: https://anti-ad.net/easylist.txt
  name: Anti-AD
  id: 1607147734
- enabled: true
  url: https://www.i-dont-care-about-cookies.eu/abp/
  name: IDCA Cookies
  id: 1607147735
- enabled: true
  url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
  name: Adblock Warning Removal List
  id: 1630399212
whitelist_filters: []
user_rules:
- '@@||*.p2p.huya.com^'
- '@@||bdtj.tagtic.cn^'
- '@@||pv.sohu.com^'
- '@@||ltetest*.139site.com^'
- '@@||g1.tagtic.cn^'
- '||st0.dancf.com^'
- '||background.cowtransfer.com^'
- '||background.c-t.work^'
- ""
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 10
